CREATE TABLE player_stats(
    player_name TEXT,
    player_id BIGINT,
    year INT,
    pa INT,
    k_percent NUMERIC,
    bb_percent NUMERIC,
    batting_avg NUMERIC,
    slg_percent NUMERIC,
    on_base_percent NUMERIC,
    xba NUMERIC,
    xslg NUMERIC,
    woba NUMERIC,
    xwoba NUMERIC,
    xobp NUMERIC,
    sweet_spot_percent NUMERIC,
    barrel_batted_rate NUMERIC,
    hard_hit_percent NUMERIC,
    avg_best_speed NUMERIC,
    avg_hyper_speed NUMERIC,
    woba_xwoba_diff NUMERIC,
    slg_xslg_diff NUMERIC,
    obp_xobp_diff NUMERIC
);